const books = [
  { id: 1, title: "O Senhor dos Anéis", author: "J.R.R. Tolkien", price: 59.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 2, title: "1984", author: "George Orwell", price: 29.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 3, title: "Dom Casmurro", author: "Machado de Assis", price: 24.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 4, title: "Harry Potter e a Pedra Filosofal", author: "J.K. Rowling", price: 39.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 5, title: "Cem Anos de Solidão", author: "Gabriel García Márquez", price: 34.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 6, title: "A Revolução dos Bichos", author: "George Orwell", price: 19.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 7, title: "O Pequeno Príncipe", author: "Antoine de Saint-Exupéry", price: 15.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 8, title: "Crime e Castigo", author: "Fiódor Dostoiévski", price: 45.00, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 9, title: "Orgulho e Preconceito", author: "Jane Austen", price: 27.50, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 10, title: "O Hobbit", author: "J.R.R. Tolkien", price: 42.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 11, title: "A Metamorfose", author: "Franz Kafka", price: 22.00, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 12, title: "Duna", author: "Frank Herbert", price: 49.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 13, title: "O Alquimista", author: "Paulo Coelho", price: 29.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 14, title: "Memórias Póstumas de Brás Cubas", author: "Machado de Assis", price: 25.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 15, title: "O Grande Gatsby", author: "F. Scott Fitzgerald", price: 32.00, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 16, title: "Sapiens: Uma Breve História da Humanidade", author: "Yuval Noah Harari", price: 54.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 17, title: "A Guerra dos Tronos", author: "George R.R. Martin", price: 65.00, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 18, title: "O Nome do Vento", author: "Patrick Rothfuss", price: 47.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 19, title: "A Menina que Roubava Livros", author: "Markus Zusak", price: 34.50, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 20, title: "O Conde de Monte Cristo", author: "Alexandre Dumas", price: 55.00, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 21, title: "A Divina Comédia", author: "Dante Alighieri", price: 39.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 22, title: "A Cidade do Sol", author: "Khaled Hosseini", price: 36.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 23, title: "Neuromancer", author: "William Gibson", price: 29.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 24, title: "O Morro dos Ventos Uivantes", author: "Emily Brontë", price: 28.00, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 25, title: "Fahrenheit 451", author: "Ray Bradbury", price: 26.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 26, title: "As Crônicas de Nárnia", author: "C.S. Lewis", price: 49.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 27, title: "O Diário de Anne Frank", author: "Anne Frank", price: 24.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 28, title: "Os Miseráveis", author: "Victor Hugo", price: 59.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 29, title: "A Ilíada", author: "Homero", price: 35.00, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 30, title: "O Processo", author: "Franz Kafka", price: 27.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 31, title: "A Odisséia", author: "Homero", price: 34.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 32, title: "O Estrangeiro", author: "Albert Camus", price: 23.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 33, title: "O Retrato de Dorian Gray", author: "Oscar Wilde", price: 29.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 34, title: "Admirável Mundo Novo", author: "Aldous Huxley", price: 31.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 35, title: "A Redoma de Vidro", author: "Sylvia Plath", price: 28.50, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 36, title: "O Apanhador no Campo de Centeio", author: "J.D. Salinger", price: 27.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 37, title: "O Sol é para Todos", author: "Harper Lee", price: 34.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 38, title: "As Vinhas da Ira", author: "John Steinbeck", price: 39.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 39, title: "O Lobo da Estepe", author: "Hermann Hesse", price: 26.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 40, title: "A Peste", author: "Albert Camus", price: 29.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 41, title: "A Fundação", author: "Isaac Asimov", price: 44.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 42, title: "O Silmarillion", author: "J.R.R. Tolkien", price: 49.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 43, title: "A Mão Esquerda da Escuridão", author: "Ursula K. Le Guin", price: 32.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 44, title: "A Coragem de Ser Imperfeito", author: "Brené Brown", price: 29.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 45, title: "O Poder do Hábito", author: "Charles Duhigg", price: 39.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 46, title: "A Arte da Guerra", author: "Sun Tzu", price: 19.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 47, title: "Homo Deus", author: "Yuval Noah Harari", price: 54.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 48, title: "O Principezinho", author: "Antoine de Saint-Exupéry", price: 15.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 49, title: "A Longa Caminhada", author: "Stephen King", price: 34.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" },
  { id: 50, title: "O Iluminado", author: "Stephen King", price: 39.90, image: "https://via.placeholder.com/150", imageMobile: "https://via.placeholder.com/100" }
];